DROP TABLE IF EXISTS Huutaja CASCADE;
DROP TABLE IF EXISTS Valitaulu CASCADE;
DROP TABLE IF EXISTS Asia CASCADE;
DROP TABLE IF EXISTS Valitustaulu2 CASCADE;
DROP TABLE IF EXISTS AsiaKategoriat CASCADE;